name: Release

on:
  # Runs when a release is created
  release:
    types: [created]

jobs:
  # Build job
  build:
    strategy:
      matrix:
        environment: ['dev', 'uat', 'prod']
    uses: ./.github/workflows/build.yaml
    with:
      # Build for all environments
      environment: ${{ matrix.environment }}
    secrets: inherit

  # # Deploy to Azure UAT job
  # deploy-azure-uat:
  #   needs: build
  #   uses: ./.github/workflows/deploy_to_azure.yaml
  #   with:
  #     build_name: uat-build-${{ github.ref_name }}
  #     environment: uat
  #   secrets: inherit

  # Create GitHub release job
  create-release:
    needs: ['build'] #, 'deploy-azure-uat']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Dev Build
        uses: actions/download-artifact@v4
        with:
          name: dev-build-${{ github.ref_name }}
          path: ./dev

      - name: Download UAT Build
        uses: actions/download-artifact@v4
        with:
          name: uat-build-${{ github.ref_name }}
          path: ./uat

      - name: Download Prod Build
        uses: actions/download-artifact@v4
        with:
          name: prod-build-${{ github.ref_name }}
          path: ./prod

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Update CHANGELOG
        id: update_changelog
        run: |
          echo "## [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})" >> CHANGELOG.md
          echo "${{ github.event.release.body }}" >> CHANGELOG.md
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git commit -m "Add changes for ${{ github.event.release.tag_name }} release"
          git push origin HEAD:master

      - name: Upload Dev Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dev/dev-build-${{ github.ref_name }}.zip
          asset_name: dev-build-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload UAT Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./uat/uat-build-${{ github.ref_name }}.zip
          asset_name: uat-build-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload Prod Build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./prod/prod-build-${{ github.ref_name }}.zip
          asset_name: prod-build-${{ github.ref_name }}.zip
          asset_content_type: application/zip