name: Release

on:
  # Runs when a commit is tagged
  push:
    tags:
      - 'v*.*.*'

jobs:
  # Build job
  build:
    strategy:
      matrix:
        environment: ['dev', 'uat', 'prod']
    uses: ./.github/workflows/build.yaml
    with:
      # Build for all environments
      environment: ${{ matrix.environment }}
    secrets: inherit

  # Create GitHub release job
  create-draft-release:
    needs: ['build'] #, 'deploy-azure-uat']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create draft release
        id: create_draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }} Release
          body: |
            ## Changes

          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_draft_release.outputs.upload_url }}
      id: ${{ steps.create_draft_release.outputs.id }}

  upload-release-assets:
    needs: ['create-draft-release']
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['dev', 'uat', 'prod']
    steps:
      - name: Download ${{ matrix.environment }} Build
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.environment }}-build-${{ github.ref_name }}
          path: ./${{ matrix.environment }}

      - name: Compress ${{ matrix.environment }} Build
        run: |
          zip -r ./${{ matrix.environment }}-build-${{ github.ref_name }}.zip ./${{ matrix.environment }}

      - name: Upload ${{ matrix.environment }} Build
        if: success()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-draft-release.outputs.upload_url }}
          asset_path: ./${{ matrix.environment }}-build-${{ github.ref_name }}.zip
          asset_name: ${{ matrix.environment }}-build-${{ github.ref_name }}.zip
          asset_content_type: application/zip

  # Publish release job
  publish-release:
    needs: ['create-draft-release', 'upload-release-assets']
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        if: success()
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const release_id = ${{ needs.create_draft_release.outputs.id }}
            await github.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id,
              draft: false
            })

  # Deploy to Azure UAT job
  deploy-azure-uat:
    needs: ["build", "publish-release"]
    uses: ./.github/workflows/deploy_to_azure.yaml
    with:
      build_name: uat-build-${{ github.ref_name }}
      environment: uat
    secrets: inherit